### PR TITLE
Run with the latest version of clojure, alpha15

### PR DESCRIPTION
**Pull request by Rovanion**
Alpha 15 has been released. I didn't find any further mentions of the number 14 in the source code.

### CODE REVIEW

**Comment by muhuk** [comment]
Change is fine. Do you expect more alphas to come or would you agree with me if I suggested waiting for the actual release?

**Comment by Rovanion** [comment]
I've heard talks that both the error messages and performance is going to get some work so no, I don't agree. But then again I don't actually work at cognitect and have no insight.

**Comment by muhuk** [comment]
Sure. I will check if other libs got newer versions, run the benchmark and update its website in the weekend.

**Comment by Rovanion** [comment]
Cool!

2017-03-29 3:21 GMT+03:00 Atamert Ölçgen <notifications@github.com>:

**Comment by muhuk** [comment]
Haven't had the chance to run it. I will do it this weekend latest. If life permits.

**Comment by muhuk** [comment]
Run the benchmark, updated the report page. Raw results are [here](https://gist.github.com/muhuk/2bc38ce55da580e967a3fb5946d9ba4b).

**Pull request merged**
